"""Minimal Loughran-McDonald lexicon fallback (offline, committed).

The official LM Master Dictionary (Loughran & McDonald 2011, *Journal of
Finance*) contains thousands of words per sentiment category. To keep the test
suite and CI fully offline, this module ships a small, representative subset
(~40 words per category) drawn from the published dictionary. It is used only
when ``data/raw/lm_master_dictionary.csv`` is absent.

All words are upper-cased to match the convention of the official file.
"""

from __future__ import annotations

NEGATIVE: frozenset[str] = frozenset(
    {
        "ABANDON",
        "ABANDONED",
        "ADVERSE",
        "ADVERSELY",
        "AGAINST",
        "BAD",
        "BANKRUPTCY",
        "BREACH",
        "CLOSED",
        "CLOSING",
        "CONCERN",
        "DECLINE",
        "DECLINED",
        "DECREASE",
        "DEFAULT",
        "DEFICIT",
        "DELAY",
        "DEPRESSED",
        "DETERIORATE",
        "DIFFICULT",
        "DISCLOSE",
        "DISMISS",
        "DOWNTURN",
        "FAIL",
        "FAILED",
        "FAILURE",
        "FRAUD",
        "HARM",
        "IMPAIRMENT",
        "LOSS",
        "LOSSES",
        "NEGATIVE",
        "POOR",
        "PROBLEM",
        "RESTATE",
        "SEVERE",
        "SHORTFALL",
        "SLOWDOWN",
        "TERMINATION",
        "WEAKNESS",
    }
)

UNCERTAINTY: frozenset[str] = frozenset(
    {
        "ALMOST",
        "AMBIGUITY",
        "AMBIGUOUS",
        "APPARENT",
        "APPARENTLY",
        "APPROXIMATE",
        "APPROXIMATELY",
        "ASSUME",
        "ASSUMED",
        "ASSUMPTION",
        "BELIEVE",
        "CONTINGENCY",
        "CONTINGENT",
        "COULD",
        "DEPEND",
        "DEPENDS",
        "DOUBT",
        "EXPOSURE",
        "FLUCTUATE",
        "FLUCTUATION",
        "INDEFINITE",
        "INTANGIBLE",
        "LIKELIHOOD",
        "MAY",
        "MAYBE",
        "MIGHT",
        "NEARLY",
        "PENDING",
        "POSSIBLE",
        "POSSIBLY",
        "PRELIMINARY",
        "PROBABLE",
        "RISK",
        "RISKS",
        "RISKY",
        "SOMETIMES",
        "SUDDEN",
        "TENTATIVE",
        "UNCERTAIN",
        "UNCERTAINTY",
        "UNKNOWN",
        "UNPREDICTABLE",
        "VARY",
        "VOLATILITY",
    }
)

LITIGIOUS: frozenset[str] = frozenset(
    {
        "ADJUDICATE",
        "ALLEGATION",
        "ALLEGE",
        "ALLEGED",
        "AMENDED",
        "APPEAL",
        "ARBITRATION",
        "ATTORNEY",
        "CLAIM",
        "CLAIMANT",
        "CLAIMS",
        "CONTRACT",
        "CONTRACTUAL",
        "COURT",
        "COURTS",
        "DAMAGES",
        "DEFENDANT",
        "DEPOSITION",
        "INDEMNIFICATION",
        "INDEMNIFY",
        "JUDICIAL",
        "JURISDICTION",
        "JURY",
        "LAWSUIT",
        "LAWSUITS",
        "LEGAL",
        "LIABILITY",
        "LITIGATION",
        "PETITION",
        "PLAINTIFF",
        "PROSECUTION",
        "REGULATION",
        "REGULATORY",
        "SETTLEMENT",
        "STATUTE",
        "STATUTORY",
        "SUBPOENA",
        "SUE",
        "SUED",
        "TESTIMONY",
        "TORT",
        "TRIAL",
    }
)

__all__ = ["NEGATIVE", "UNCERTAINTY", "LITIGIOUS"]
