"""Assemble the LaTeX research note and compile it to PDF.

The document is built by string assembly (no template engine dependency). All
dynamic text is LaTeX-escaped. Compilation prefers ``tectonic`` (self-contained,
trivial in CI) and falls back to ``pdflatex``; if neither is installed the ``.tex``
source is still written so the artifact is never lost.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
from pathlib import Path

from reporting.data import ReportData, SignalResult, signal_label

logger = logging.getLogger(__name__)

_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def _esc(text: str) -> str:
    """Escape LaTeX special characters in arbitrary text."""
    out = []
    for ch in str(text):
        out.append(_ESCAPES.get(ch, ch))
    return "".join(out)


def _results_table(data: ReportData) -> str:
    """Render the per-form results as a booktabs table."""
    header = (
        "\\begin{tabular}{llrrrrc}\n"
        "\\toprule\n"
        "Form & Signal & Horizon & IC & IC $t$ & L-S \\% & Spread $t$ \\\\\n"
        "\\midrule\n"
    )
    body_rows: list[str] = []
    ordered = sorted(
        (r for r in data.signal_results if r.n_obs > 0),
        key=lambda r: (r.form, -abs(r.spread_tstat)),
    )
    current_form: str | None = None
    for r in ordered:
        if current_form is not None and r.form != current_form:
            body_rows.append("\\midrule\n")
        current_form = r.form
        body_rows.append(
            f"{_esc(r.form)} & {_esc(signal_label(r.signal))} & {r.horizon_days}d & "
            f"{r.ic:.3f} & {r.ic_tstat:.2f} & {r.ls_spread * 100:.2f} & "
            f"{r.spread_tstat:.2f}{_esc(r.stars)} \\\\\n"
        )
    footer = "\\bottomrule\n\\end{tabular}"
    return header + "".join(body_rows) + footer


def _figure_block(caption: str, rel_path: str, width: str = "0.85") -> str:
    """Render a centered figure include."""
    return (
        "\\begin{figure}[ht]\n\\centering\n"
        f"\\includegraphics[width={width}\\textwidth]{{{rel_path}}}\n"
        f"\\caption{{{_esc(caption)}}}\n"
        "\\end{figure}\n"
    )


def _headline_sentence(headline: SignalResult | None) -> str:
    """One-line abstract of the strongest 10-K result."""
    if headline is None:
        return "No 10-K results were available to summarise."
    return (
        f"The strongest 10-K signal is {_esc(signal_label(headline.signal))} at a "
        f"{headline.horizon_days}-day horizon (IC {headline.ic:.3f}, long-short spread "
        f"{headline.ls_spread * 100:.2f}\\% net of cost, $t = {headline.spread_tstat:.2f}$)."
    )


def build_tex(data: ReportData, figures: dict[str, Path], narrative: str) -> str:
    """Assemble the full LaTeX source for the research note.

    Args:
        data: Resolved report data.
        figures: Mapping of figure key to PNG path (relative to the .tex file's
            directory once written, i.e. ``figures/<name>.png``).
        narrative: Plain-text interpretation paragraphs.

    Returns:
        The complete ``.tex`` document as a string.
    """
    start, end = data.date_range
    span = f"{start} to {end}" if start and end else "n/a"
    filings_desc = ", ".join(f"{c} {f}" for f, c in sorted(data.n_filings_by_form.items()))
    headline = data.headline()

    captions = {
        "ic": "Information coefficient by signal (10-K). Bars coloured by t-statistic "
        "magnitude: green significant, amber suggestive, grey noise.",
        "spread": "Event-study long-short tercile spread by signal (10-K), net of cost.",
        "equity_curve": "Event-ordered cumulative long-short return for the headline "
        "signal. A visualisation of the tercile spread, not a tradeable curve.",
        "feature_importance": "Walk-forward model feature importances (10-K).",
    }

    narrative_tex = "\n\n".join(_esc(p) for p in narrative.split("\n\n") if p.strip())

    figure_section = ""
    for key in ("ic", "spread", "equity_curve", "feature_importance"):
        if key in figures:
            rel = "figures/" + figures[key].name
            figure_section += _figure_block(captions[key], rel)

    return rf"""\documentclass[11pt]{{article}}
\usepackage[margin=1in]{{geometry}}
\usepackage{{graphicx}}
\usepackage{{booktabs}}
\title{{FilingAlpha --- SEC Filing Signal Research Note}}
\author{{Generated by the FilingAlpha pipeline}}
\date{{{_esc(str(data.generated_at))}}}
\begin{{document}}
\maketitle

\begin{{abstract}}
A backtest of classical natural-language signals extracted from SEC filings,
evaluated against market-adjusted forward returns with strict filing-lag (no
lookahead). Universe: {_esc(str(data.n_companies))} companies; filings:
{_esc(filings_desc)}; sample span: {_esc(span)}. {_headline_sentence(headline)}
\end{{abstract}}

\section{{Methodology}}
Each signal is computed per filing and aligned to the firm's forward return over
21- and 63-trading-day horizons, entered on the first trading day strictly after
the filing date. Returns are market-adjusted (excess of SPY over the identical
window). Signals are evaluated by Spearman information coefficient (with a
$t$-statistic) and by an event-study long-short tercile spread, net of 10 bps per
side. 10-K and 10-Q filings are evaluated separately, since the text-change
signals are an annual-report phenomenon. A significance marker of $*$ denotes
$|t| \ge 1.5$ and $**$ denotes $|t| \ge 2$.

\section{{Results}}
\begin{{center}}
{_results_table(data)}
\end{{center}}

{figure_section}

\section{{Interpretation}}
{narrative_tex}

\section{{Honest caveats}}
This is a measurement harness, not a deployed strategy. At this universe size the
results are not expected to reach statistical significance; the value is the
leakage-free, point-in-time-correct construction and an honest reporting of weak
or null effects. Scaling the universe to several hundred small- and mid-cap firms
is the principled path to significance and is left as future work.

\end{{document}}
"""


def compile_pdf(tex_path: Path) -> Path | None:
    """Compile a ``.tex`` file to PDF if a LaTeX engine is available.

    Args:
        tex_path: Path to the ``.tex`` source.

    Returns:
        Path to the generated PDF, or ``None`` if no engine is installed or
        compilation failed.
    """
    # Resolve to absolute paths so the engine works regardless of the process's
    # working directory (figures are referenced relative to the .tex's own dir).
    tex_path = tex_path.resolve()
    out_dir = tex_path.parent
    tectonic = shutil.which("tectonic")
    if tectonic:
        cmd = [tectonic, "--keep-logs", "--outdir", str(out_dir), str(tex_path)]
    elif shutil.which("pdflatex"):
        cmd = [
            "pdflatex",
            "-interaction=nonstopmode",
            "-output-directory",
            str(out_dir),
            str(tex_path),
        ]
        # MiKTeX refuses to auto-install packages until its update check passes,
        # which breaks non-interactive builds. The document needs only base
        # packages, so disable on-the-fly installation and use what is present.
        try:
            version = subprocess.run(
                ["pdflatex", "--version"], capture_output=True, text=True, check=False
            )
            if "MiKTeX" in (version.stdout or ""):
                cmd.insert(1, "-disable-installer")
        except OSError:  # pragma: no cover - probing is best-effort
            pass
    else:
        logger.warning("No LaTeX engine (tectonic/pdflatex) found; wrote .tex only.")
        return None

    pdf_path = tex_path.with_suffix(".pdf")
    try:
        # pdflatex needs two passes for references; run twice harmlessly.
        runs = 1 if tectonic else 2
        for _ in range(runs):
            subprocess.run(cmd, check=True, capture_output=True, cwd=out_dir)
    except subprocess.CalledProcessError as exc:  # pragma: no cover - env-dependent
        logger.error("LaTeX compilation failed: %s", exc.stderr.decode("utf-8", "ignore")[-800:])
        return None
    if pdf_path.exists():
        logger.info("Compiled report PDF: %s", pdf_path)
        return pdf_path
    return None


def write_report(
    data: ReportData, figures: dict[str, Path], narrative: str, out_dir: Path
) -> dict[str, Path]:
    """Write the ``.tex`` source and compile it to PDF when possible.

    Args:
        data: Resolved report data.
        figures: Figure key to PNG path mapping.
        narrative: Interpretation prose.
        out_dir: Directory to write ``report.tex`` (and ``report.pdf``) into.

    Returns:
        Mapping with a ``tex`` key always, and a ``pdf`` key when compilation
        succeeded.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    tex = build_tex(data, figures, narrative)
    tex_path = out_dir / "report.tex"
    tex_path.write_text(tex, encoding="utf-8")
    logger.info("Wrote LaTeX source: %s", tex_path)

    outputs = {"tex": tex_path}
    pdf = compile_pdf(tex_path)
    if pdf is not None:
        outputs["pdf"] = pdf
    return outputs


__all__ = ["build_tex", "compile_pdf", "write_report"]
